### ISSUE TITLE
F# Permutations Library

### ISSUE THREAD

**Issue by shaunluttin** [fsprojects/.github#16]
We have been working on this for about 100 hours now. It's been a good vehicle for learning F# and also might be of use to the community: 

https://github.com/shaunluttin/algorithms/tree/master/articles/functional-programs-for-generating-permutations

The FSharp solution contains implementations and tests of permutation algorithms from this paper: 

https://github.com/shaunluttin/algorithms/blob/master/articles/functional-programs-for-generating-permutations/article.pdf

**Comment by dsyme** [comment]
@shaunluttin  Apologies we missed this. Did you transfer in? You should be able to do it directly?

**Comment by dsyme** [comment]
Closing this old issue
