### ISSUE TITLE
Policy on "fork-and-reboot-in-fsprojects" proposals

### ISSUE THREAD

**Issue by dsyme** [fsprojects/.github#41]
@sergey-tihon From time to time people ask if it would be possible to fork-and-reboot an apparently-abandoned F# community project (e.g. in a personal repository) into fsprojects.

In general in the past we've never had to do this as project owners have either decided to move in or not.  However it's a scenario we should think about, and probably have some reasonable policy guidelines.

Some notes:
* Fork-and-reboot on active projects is generally really bad, but is seen as reasonable for abandoned projects.
* Forking loses issues, PRs etc. Also loses access to be able to publish nuget packages and will lose package continuity  

cc @cartermp

**Comment by sergey-tihon** [comment]
I think that we anyway try to contact original author and try to make a proper transfer.

So process may look like:
1. Person who volunteer themself to be a new maintainer should create issue in this repo 
2. We will process such requests case by case and will try to contact owner using available channels.
3. If we do not receive response from the author in 1-2 month then we do official fork on behalf of fsprojects
4. We should keep credits in README and probably link to the issue in this project to keep track for a reasons for our behavior
5. We also need clear definition about what we count as abandoned (no commits for 1+/2 years and no response on issues from maintainer)

**Comment by dsyme** [comment]
Also offer a path back to reunion with the original project. And an open invitation for the originator to join back as a co-maintainer (or even have the project back if they want to resume repo duties)
