### ISSUE TITLE
Move FSharp.Json to fsprojects

### ISSUE THREAD

**Issue by vsapronov** [fsprojects/.github#43]
https://github.com/vsapronov/FSharp.Json/issues/65 and https://github.com/vsapronov/FSharp.Json/issues/61#issuecomment-1290458265

**Comment by dsyme** [comment]
@vsapronov Fab - could you nominate one or two people to be maintainers please, possibly including yourself if you plan to keep doing it?

Once we have that just transfer the project in using "transfer project" , I believe you will have permissions if a member of this org

**Comment by dsyme** [comment]
@vsapronov I've invited you to the fsprojects org - if yo uaccept you should be able to transfer in.  We'll then sort out permissions, thanks

We will need the name of one co-maintainer

**Comment by dsyme** [comment]
OK, cool, we have @tnishimura and @johnazariah stepping up as co-maintainers.

@vsapronov is that OK for you and if so can you do the repo transfer please? Thanks!

**Comment by vsapronov** [comment]
@dsyme I have tried though I see "You don’t have the permission to create public repositories on fsprojects". Could you please grant permissions.
Also you will make me admin of the project afterwards, right?

**Comment by dsyme** [comment]
@vsapronov Try again now please, something has changed with GH permissions that members can no longer transfer in, I think I've fixed that.

> Also you will make me admin of the project afterwards, right?

Yes, absolutely, the original creator is always welcome to be admin or maintainer.  If you decide you want to no longer be admin then whoever is maintainer will have "maintainer" rights.

**Comment by vsapronov** [comment]
OK, transfer is done.

**Comment by sergey-tihon** [comment]
@vsapronov thanks, you Admin access is restored.

**Comment by dsyme** [comment]
Welcome along @vsapronov! Long live FSharp.Json!

**Comment by johnazariah** [comment]
Hooray! :)
